apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-web-server
  labels:
    app: k8s-web-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s-web-server
  template:
    metadata:
      labels:
        app: k8s-web-server
    spec:
      containers:
      - name: k8s-web-server
        image: aymanelmalah/k8s-web-server:latest
        ports:
        - containerPort: 3000 